### ISSUE TITLE
Syntax errors in YAML causes failure to unlock

### ISSUE THREAD

**Issue by Immortalin** [nzaillian/django-encrypted-secrets#1]
E.g. mistyping `:` as `-` would result in `edit_secrets` failing until all `get_secret` lines in django application are commented out.

**Comment by nzaillian** [comment]
Hmm, I may misunderstand the issue described but it sounds like this is the behavior we should want? Alternatively we could throw an exception if the YAML syntax is invalid - I do think that just swallowing the error would be worse

**Comment by nzaillian** [comment]
This is addressed now with https://github.com/nzaillian/django-encrypted-secrets/pull/2 (`YAMLFormatException` is raised if in yaml mode and if invalid yaml formatting is detected when parsing the encrypted secrets file).
