### ISSUE TITLE
pycrypto is discontinued and is no longer actively supported

### ISSUE THREAD

**Issue by mjlabe** [nzaillian/django-encrypted-secrets#3]
When trying to use this on Windows, pycrypto failed to install. When I looked up the error, I saw:

> It is old and not maintained and contains many vulnerabilities. Use pycryptodome (https://github.com/Legrandin/pycryptodome) instead - it is compatible and up to date.

[https://github.com/dlitz/pycrypto/issues/173](url)

**Comment by nzaillian** [comment]
I updated the dependency, which seems to be API compatible as far as the usages here so seems to be working, with tests passing. Merged as https://github.com/nzaillian/django-encrypted-secrets/pull/4 and pushed to PyPI as v0.9.6 (https://pypi.org/project/django-encrypted-secrets/#history). Hopefully that fixes the issue but let me know if not
